[app]
port = 3000

statuses = [
    "expired",
    "online",
    "pending",
]

[JWT]
secret = ""

[cloudflare]
cf_apikey = ""
account_id = ""

[discord]
username = ""
webhook = ""

[redis]
hostname = ""
port = 6379
password = ""

[mongodb]
string = ""